IMO-1: Prepare the husky commit rules.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -4,12 +4,15 @@
 echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
 echo 'please be patient, this may take a while...'
 
-# COMMIT_PATTERN = '(^IMO-[1-9][0-9]*:[[:space:]]?.*\.$)'
+COMMIT_PATTERN="^IMO-[1-9][0-9]*:[[:space:]]?.*\.$"
 
-msg=$(cat $1 | sed '/^#.*/d')
-if ! [[ "$msg" =~ $PATTERN_COMMITS ]]; then
-  echo -e "\x1b[31mError commit message:\x1b[0m \x1b[33m"$msg"\x1b[0m does not follow conventional commit standard, e.g \x1b[33m 'IMO-1234: Play the commit game.' \x1b[33m"
-  exit 1;
+msg=$(cat .git/COMMIT_EDITMSG | sed '/^#.*/d')
+
+echo "Debug: Commit message is: $msg"
+if ! echo "$msg" | grep -qE "$COMMIT_PATTERN"; then
+  echo "Debug: Commit message does not match pattern."
+  echo -e "Error commit message: $msg does not follow the conventional commit standard, e.g.  'IMO-1234: Play the commit game.' "
+  false
 fi
  
 # Check ESLint Standards
@@ -28,6 +31,7 @@ yarn test ||
     false;
 )
 
+yarn format
  
 echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
  
